apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: [app_name]
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: [app_image]:[tag]